# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5584d18080415b865d39e7f5cf60e5c84336deb9513754550797a1437aab9b8be2ab110560a149020a48fb3a96410ff949fb6d438ad4b900882d24eb9730cecf

test:
  secret_key_base: cab8a9aa195ebcbb95cc17b387b64a5f4ea469538286aa147685778fb8f9dcf248f70a5a9db06cf894ad052a455bb5c7c69c008cc8bb467989a5f64876305fbe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
